/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as KarachiRouteImport } from './routes/karachi'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TalentSlugRouteImport } from './routes/talent.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const KarachiRoute = KarachiRouteImport.update({
  id: '/karachi',
  path: '/karachi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentSlugRoute = TalentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TalentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/karachi': typeof KarachiRoute
  '/services': typeof ServicesRoute
  '/talent': typeof TalentRouteWithChildren
  '/work': typeof WorkRoute
  '/talent/$slug': typeof TalentSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/karachi': typeof KarachiRoute
  '/services': typeof ServicesRoute
  '/talent': typeof TalentRouteWithChildren
  '/work': typeof WorkRoute
  '/talent/$slug': typeof TalentSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/karachi': typeof KarachiRoute
  '/services': typeof ServicesRoute
  '/talent': typeof TalentRouteWithChildren
  '/work': typeof WorkRoute
  '/talent/$slug': typeof TalentSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/karachi'
    | '/services'
    | '/talent'
    | '/work'
    | '/talent/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/karachi'
    | '/services'
    | '/talent'
    | '/work'
    | '/talent/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/karachi'
    | '/services'
    | '/talent'
    | '/work'
    | '/talent/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  KarachiRoute: typeof KarachiRoute
  ServicesRoute: typeof ServicesRoute
  TalentRoute: typeof TalentRouteWithChildren
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karachi': {
      id: '/karachi'
      path: '/karachi'
      fullPath: '/karachi'
      preLoaderRoute: typeof KarachiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$slug': {
      id: '/talent/$slug'
      path: '/$slug'
      fullPath: '/talent/$slug'
      preLoaderRoute: typeof TalentSlugRouteImport
      parentRoute: typeof TalentRoute
    }
  }
}

interface TalentRouteChildren {
  TalentSlugRoute: typeof TalentSlugRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentSlugRoute: TalentSlugRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  KarachiRoute: KarachiRoute,
  ServicesRoute: ServicesRoute,
  TalentRoute: TalentRouteWithChildren,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
